config/routes.rb
BlogApp::Application.routes.draw do
  get "blog/index"

  devise_for :users, skip: :registrations

  root to: 'blogs#index'
  resource :blog, only: [:edit, :update] do 
  	get 'page/:page', action: :index, on: :collection
  end
  resources :posts do 
    resources :comments, only: [:create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, :all
    else
      can :comment, Post do |post|
        post.comments_enabled?
      end
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :subtitle, :title
  validates_inclusion_of :singleton_guard, in: [0]
  validates :title, :subtitle, presence: true
  has_many :posts

  def add_entry

  end

  def entries
  	posts
  end

  def tags 
    Post.tag_counts_on(:tags)
  end

  def self.instance
  	first || Blog.create(title: "Default Blog Title", subtitle: "Subtitle of a default blog")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope order('created_at DESC')
  attr_accessible :author, :body
  belongs_to :post
  validate :author, :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope order("created_at DESC").includes(:comments, :tags)
  attr_accessible :body, :title, :comments_enabled, :tag_list
  belongs_to :blog
  validates :body, :title, presence: true
  has_many :comments, dependent: :destroy

  acts_as_taggable

  extend FriendlyId
  friendly_id :title, use: [:slugged]

  def comments_enabled?
  	!!comments_enabled
  end

  def add_comment(comment)
  	comment = comments.build(comment)
  end

  def next
    blog.entries.where("id > ?", id).order("id ASC").first.try(:id)
  end

  def prev
    blog.entries.where("id < ?", id).order("id DESC").first.try(:id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_blog

  private 
  def load_blog
  	@blog = Blog.instance
  end

  def markdown(body, extensions = {})
  	renderer = RenderVideoLinks.new
  	md = Redcarpet::Markdown.new(renderer, extensions)
  	md.render(body).html_safe
  end
  helper_method :markdown
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!, except: :index
  def index
  	@entries = with_tags.page(params[:page])
  end

  def edit
  	#@blog	
  end

  def update
  	if @blog.update_attributes(params[:blog])
  		respond_with @blog, location: root_path, notice: "Blog Settings Updated!"
  	else
  		render :edit
  	end
  end

  private
  def with_tags
    return @blog.entries.tagged_with(params[:tag]) if params[:tag].present?
    @blog.entries
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :html, :js
	before_filter :authorize_post

	def create
		@comment = @post.add_comment(params[:comment]).decorate
		flash[:notice]="Comment Created!" if @comment.save
		respond_with @post
	end

	private 
	def authorize_post
		@post = @blog.entries.find(params[:post_id])
		authorize! :comment, @post
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, except: :show
	respond_to :html
	def show
		@post = @blog.entries.find(params[:id]).decorate
		respond_with @post
	end

	def new
		@post = Post.new
	end

	def create
		@post = @blog.entries.build(params[:post])
		flash[:notice] = "Post Created!" if @post.save
		respond_with @post
	end

	def edit
		@post = @blog.entries.find(params[:id])
	end

	def update
		@post = @blog.entries.find(params[:id])
		flash[:notice]= "Post Updated!" if @post.update_attributes(params[:post])
		respond_with @post
	end

	def destroy
		@post = @blog.entries.find(params[:id])
		flash[:notice] = "Post Destroyed!" if @post.destroy
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_entry.html.haml
%li
	.entry
		%h3= entry.title
		%h5= entry.created_at
		%p
			tags:
			= entry.tag_list.to_s
		%p= entry.body.truncate(160)
		=link_to "Read More...", post_path(entry)

app/views/blogs/edit.html.haml
=semantic_form_for @blog, url: blog_path, method: :put do |f|
	=f.inputs do 
		=f.input :title
		=f.input :subtitle
	=f.actions do 
		=f.action :submit, label: "Edit Blog"

app/views/blogs/index.html.haml
.entries.twelve.columns
	%ul
		=render partial: 'entry', collection: @entries
	=paginate @entries
.four.columns
	%h5 tags
	=render_cell :tag_cloud, :display, tags: @blog.tags

app/views/comments/_comment.html.haml
%li
	%h5= comment.author
	%h6= comment.created_at
	%p= comment.body

app/views/comments/_form.html.haml
%h5 comment form
=semantic_form_for [post, Comment.new], remote: true do |f|
	=f.inputs do 
		=f.input :author, input_html: {hint: "Anonymous"}
		=f.input :body, input_html: {rows: 5}
	=f.actions do 
		=f.action :submit, label: "Leave a comment"

app/views/comments/create.js.erb
$('ul.comments').prepend("<%=j render partial: 'comment', object: @comment%>")

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title BlogApp
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		.container
			.header.row
				%h2= @blog.title
				%h4= @blog.subtitle
				.flash
					-flash.each do |k,v|
						%p{class: "#{k.to_s}"}= v
			.main.row
				= yield
			.footer.row

app/views/posts/_form.html.haml
=semantic_form_for @post do |f|
	=f.inputs do 
		=f.input :title
		=f.input :body
		=f.input :tag_list, as: :string, label: "Tags format 'tag1, tag2, tag3, ...'"
		=f.input :comments_enabled, label: "Enable Comments"
	=f.actions do
		=f.action :submit, label: "Post!"

app/views/posts/_post.html.haml
.post_links.row
	%ul.post_links
		%li=link_to "<-- Newer Post", post_path(post.next) unless post.next.nil?
		%li=link_to "^ Back to blog", root_path
		
		%li=link_to "Older Post -->", post_path(post.prev) unless post.prev.nil?
		
.post.row
	%h3=post.title
	%h5=post.created_at
	%p=post.body
	-if user_signed_in?
		=link_to "Edit", edit_post_path(post)
		=link_to "Destroy", post_path(post), method: :delete, confirm: "Are you sure!?"

app/views/posts/edit.html.haml
=render partial: 'form', object: @post

app/views/posts/new.html.haml
=render partial: 'form', object: @post

app/views/posts/show.html.haml
=render partial: 'post', object: @post
.row
	.comments.ten.columns.alpha
		-if @post.comments_enabled?
			=render partial: 'comments/form', locals: {post: @post}
		-else 
			%h4 Comments have been disabled for this post
		%ul.comments
			=render partial: 'comments/comment', collection: @post.comments.decorate
	.six.columns.omega
		%h5 tags
		=render_cell :tag_cloud, :display, tags: @post.tags